### ISSUE TITLE
Switch to buttons in the "found multiple sounds" response

### ISSUE THREAD

**Issue by UncleDave** [UncleDave/DiscordSoundboardBot#43]

**Comment by stuckinab0x** [comment]
I started on this because even if we don't end up using the sound command as much, the fix involves ~~the elevator~~ two things that we're going to want anyway:

1.  Pushing additional interactions to active commands
2.  A function that takes an array and returns a `MessageComponent[]` for message options with buttons for each, accounting for the fact that discord gets angry if you attach more than 4 buttons to a row :)))))))))))))))))
